package hu.infokristaly.homework.quartz.back.model;

// Generated 2012.10.09. 11:07:05 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * QrtzCalendars generated by hbm2java
 */
@Entity
@Table(name = "QRTZ_CALENDARS")
public class QrtzCalendars implements java.io.Serializable {

    private QrtzCalendarsId id;
    private byte[] calendar;

    public QrtzCalendars() {
    }

    public QrtzCalendars(QrtzCalendarsId id, byte[] calendar) {
        this.id = id;
        this.calendar = calendar;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)), @AttributeOverride(name = "calendarName", column = @Column(name = "CALENDAR_NAME", nullable = false, length = 200)) })
    public QrtzCalendarsId getId() {
        return this.id;
    }

    public void setId(QrtzCalendarsId id) {
        this.id = id;
    }

    @Column(name = "CALENDAR", nullable = false)
    @Lob
    public byte[] getCalendar() {
        return this.calendar;
    }

    public void setCalendar(byte[] calendar) {
        this.calendar = calendar;
    }

}
